AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Resources:
  fetchSend:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-fetchSend
      Description: !Sub
        - Stack ${StackTagName} Environment ${EnvironmentTagName} Function ${ResourceName}
        - ResourceName: fetchSend
      CodeUri: src/fetchSend
      Handler: index.handler
      Runtime: nodejs10.x
      MemorySize: 3008
      Timeout: 30
      Tracing: Active
      Policies:
        - AWSXrayWriteOnlyAccess
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt Arrivals.TopicName
      Environment:
        Variables:
          TOPIC_NAME: !GetAtt Arrivals.TopicName
          TOPIC_ARN: !Ref Arrivals
  Arrivals:
    Type: AWS::SNS::Topic
  ArrivalsSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint: 3109934362
      Protocol: sms
      TopicArn: !Ref Arrivals
Parameters:
  StackTagName:
    Type: String
    Description: Stack Name (injected by Stackery at deployment time)
  EnvironmentTagName:
    Type: String
    Description: Environment Name (injected by Stackery at deployment time)